name: ETF Discord Notifier

on:
  schedule:
    - cron: '30 17 * * 1-5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas necessárias
        run: pip install yfinance requests

      - name: Executar o script Python
        run: python main.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}

